### ISSUE TITLE
Does not pass bot check

### ISSUE THREAD

**Issue by Wapweb** [Niek/playwright-addons#2]
Hi there!
Thank you for awesome library!

It seems playwright with stealth mode does not pass "Hairline feature" on https://bot.sannysoft.com/ .
I used code provided in readme:
```
(async () => {
    const browser = await require('playwright').chromium.launch({headless: false}); // or: firefox, webkit
    const addons = await import('playwright-addons');
    const page = await browser.newPage();

    await addons.adblocker(browser);
    await page.goto('https://cnn.com/');

    await addons.stealth(browser);
    await page.goto('https://bot.sannysoft.com/');
})();
```

![Untitled](https://user-images.githubusercontent.com/8421581/87224447-2c0c5700-c38e-11ea-869f-0e12fbe26f9d.png)

Playwright version is 1.2.0
Plus latest version of your library (https://github.com/Niek/playwright-addons/commit/cafb87922aa73447f628150a1216c2e31bfc5492)

Do you have any thoughts how to bypass hairline feature?

**Comment by Niek** [comment]
Thanks for the comment! The hairline check seems to be this: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/hairline.js#L18-L24

On at least my MacBook Chrome this test also fails, so I wouldn't worry too much about it.

**Comment by Wapweb** [comment]
Ok then), thank you for fast response!

In any case, i've already found a solution by checking this article https://intoli.com/blog/making-chrome-headless-undetectable/ :
```
// store the existing descriptor
const elementDescriptor = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'offsetHeight');

// redefine the property with a patched descriptor
Object.defineProperty(HTMLDivElement.prototype, 'offsetHeight', {
    ...elementDescriptor,
    get: function() {
        if (this.id === 'modernizr') {
            return 1;
        }
        return elementDescriptor.get.apply(this);
    },
});
```

**Comment by Niek** [comment]
That's actually a pretty decent workaround, I've added it to the evasions. Thanks!

@all-contributors please add @Wapweb for ideas and code

**Comment by Niek** [comment]
@all-contributors, please add @Wapweb for ideas and code

**Comment by Niek** [comment]
@all-contributors please add @Wapweb for ideas and code
